---
title: "Analysis of ZFY Spec-seq data"
author: Zheng Zuo
date: "Oct 25, 2020"
output:
  html_document:
    df_print: paged
    theme: lumen
    highlight: pygments
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---
## Loading preprocessed Spec-seq data for specificity analysis
```{r echo=TRUE, warning=FALSE, message=FALSE}
library(stringr)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggbeeswarm)
library(TFCookbook)
library(ggrepel)
library(ggalluvial)
library(magrittr)

#save.image("ZFY Spec-seq.RData")
load("data/ZFY Spec-seq.RData")


hZFY.F7_F13 %<>%
  mutate(Library = factor(purrr::map_chr(Sequence, library_type), levels = c("Reference", "R9", "R9N", "R9NN", "R10", "R11", "R12")),
         Mismatch = TFCookbook::countMismatch(Sequence, Reference.ZFY))

hZFY.F7_F13
```
## Functions used to sort binding site into each library and add finger patterns to energy logos

```{r}
Reference.ZFY = "TGGCCTAGTCGTTTTTG"
library_type <- function(seq){
  if(seq == Reference.ZFY) return("Reference")
  else if  (stringr::str_detect(seq, "T....TAGTCGTTTTTG")) return("R9")
  else if (stringr::str_detect(seq, "T....TCACGATTTTTG")) return("R9N")
  else if (stringr::str_detect(seq, "T....TCACGATTGCCC")) return("R9NN")
  else if (stringr::str_detect(seq, "TGGCC....CGTTTTTG")) return("R10")
  else if (stringr::str_detect(seq, "TGGCCTAGT....TTTG")) return("R11")
  else if (stringr::str_detect(seq, "TGGCCTAGTCGTT....")) return("R12")
  else return("Unclassified")
}

addFingers <- function(index, yMin = -1, yMax = 1, breaks = NULL){
  if(is.null(breaks))
    breaks = seq(1,100,3)
  
  fingers <- list()
  for(i in 1:length(index)){
        fingers[[2*i-1]] <- ggplot2::annotate('rect', xmin = breaks[i]-0.5, xmax = breaks[i+1] - 0.5,
                          ymin = yMin, ymax = yMax, alpha = 0.2, fill = ifelse(i%%2==1, 'grey', 'black'))
        fingers[[2*i]] <- ggplot2::annotate('text', x = breaks[i]+1, y = yMax-0.1,
                          label = paste('F', index[i], sep = "" )) 
        
  }
  return(fingers)
}
```


## Plotting energy logos for each construct
```{r fig.height=5, fig.width=10, warning=FALSE, message=FALSE}
hZFY.F11_F13 %>%
  filter(Mismatch <= 1) %>%
  TFCookbook::buildEnergyModel() %>%
  TFCookbook::getEnergyMatrix() %>%
  TFCookbook::addAnchorMatrix(anchor = "T", position = 1, height = 1) %>%
  TFCookbook::plotEnergyLogo() +
  theme(axis.text.x = element_blank(), axis.title = element_blank()) +
  scale_y_continuous(breaks = seq(-3,3)) +
  xlim(0, 18) +
  ggtitle("Energy logos for human ZFY (F11-F13)")+
  addFingers(index = 13:11, yMin = -4, yMax = 4.3, breaks = c(0, 3, 6, 8)) -> logo.hZFY.F11_F13

hZFY.F9_F13 %>%
  filter(Mismatch <= 1) %>%
  TFCookbook::buildEnergyModel() %>%
  TFCookbook::getEnergyMatrix() %>%
  TFCookbook::addAnchorMatrix(anchor = "T", position = 1, height = 1) %>%
  TFCookbook::plotEnergyLogo() +
  ggtitle("Energy logos for human ZFY (F9-F13)")+
  addFingers(index = 13:9, yMin = -2.5, yMax = 2.5, breaks = c(0, 3, 6, 8, 11, 14)) -> logo.hZFY.F9_F13

hZFY.F7_F13 %>%
  filter(Mismatch <= 1) %>%
  TFCookbook::buildEnergyModel() %>%
  TFCookbook::getEnergyMatrix() %>%
  TFCookbook::addAnchorMatrix(anchor = "T", position = 1, height = 1) %>%
  TFCookbook::plotEnergyLogo() +
  ggtitle("Energy logos for human ZFY (F7-F13)")+
  xlim(0, 18) +
  theme(axis.text.x = element_blank(), axis.title = element_blank()) +
  addFingers(index = 13:7, yMin = -2.25, yMax = 2.5, breaks = c(0, 3, 6, 8, 11, 14, 17)) -> logo.hZFY.F7_F13.single

mZFY.F7_F13 %>%
  filter(Library %in% c("Reference","R9", "R10", "R11", "R12"),
         Mismatch <= 1) %>%
  TFCookbook::buildEnergyModel() %>%
  TFCookbook::getEnergyMatrix() %>%
  TFCookbook::addAnchorMatrix(anchor = "T", position = 1, height = 1) %>%
  TFCookbook::plotEnergyLogo() + xlim(0, 18) +
  ggtitle("Energy logos for mouse ZFY (F7-F13)")+
  addFingers(index = 13:7, yMin = -2.75, yMax = 3, breaks = c(0, 3, 6, 8, 11, 14, 17)) -> logo.mZFY.F7_F13

hZFY.F1_F11 %>%
  filter(Library %in% c("Reference","R9", "R10", "R11", "R12"),
         Mismatch <= 1) %>%
  TFCookbook::buildEnergyModel() %>%
  TFCookbook::getEnergyMatrix() %>%
  TFCookbook::addAnchorMatrix(anchor = "T", position = 1, height = 1) %>%
  TFCookbook::plotEnergyLogo() +
  addFingers(index = 13:7, yMin = -2.75, yMax = 3, breaks = c(0, 3, 6, 8, 11, 14, 17, 20)) -> logo.hZFY.F1_F11

cowplot::plot_grid(logo.hZFY.F11_F13,
                   logo.hZFY.F7_F13.single,
                   #logo.mZFY.F7_F13,
                   ncol = 1,
                   align = "v", axis = "lr", rel_heights = c(1, 1))

#ggsave("Logos_ZFYs.svg", height = 9, width = 6)
```

## Plotting energy distribution of all variants under human ZFY(F7-F13) construct
```{r fig.height=5, fig.width=4, warning = FALSE}
require(ggbeeswarm)
Core.levels <- (hZFY.F7_F13 %>%
                      filter(Library %in% c("Reference", "R9")) %>% 
                      arrange(desc(Energy)))$Core

hZFY.F7_F13 %>%
  filter(Library != "Unclassified") %>%
  ggplot(aes(y =  Library, x = Energy, color = Library)) +
  geom_boxplot(notch = FALSE, outlier.shape = NA, color = "black") +
  geom_quasirandom(size = 0.5, shape = 16,  alpha = 0.8, groupOnX = FALSE) +
  xlab("Energy (kT)") + ylab("") +
  scale_color_manual(values=c("#F8766D", "#7CAE00", "#00BFC4", "#C77CFF", "#C49A00", "#00C094", "#FB61D7")) +
  scale_x_continuous(expand = c(0, 0.2), breaks = seq(-1, 5), limits = c(-1, 4)) + theme_bw()+
  scale_y_discrete(position = "left") -> plot.distribution.hZFY.F7_F13


plot.distribution.hZFY.F7_F13

#ggsave(filename = "hZFY(F7-F13) library distribution and models.svg", height = 4, width = 4.5)
```
